import type { VehicleProfile } from "./types";

export const CAR_PROFILES = {
  brezza: {
    id: "brezza",
    name: "Suzuki Brezza 2021",
    cylinders: 4,
    gears: 5,
    idleRpm: 800,
    redlineRpm: 6500,
    shiftRpm: 1500,
    baseTone: 58,
    topSpeedKph: 180,
  },
  mustang: {
    id: "mustang",
    name: "Ford Mustang V8",
    cylinders: 8,
    gears: 6,
    idleRpm: 750,
    redlineRpm: 7000,
    shiftRpm: 2800,
    baseTone: 42,
    topSpeedKph: 240,
  },
  porsche: {
    id: "porsche",
    name: "Porsche Flat-6",
    cylinders: 6,
    gears: 7,
    idleRpm: 850,
    redlineRpm: 7800,
    shiftRpm: 3000,
    baseTone: 65,
    topSpeedKph: 280,
  },
  f1: {
    id: "f1",
    name: "Formula V12",
    cylinders: 12,
    gears: 8,
    idleRpm: 2500,
    redlineRpm: 12000,
    shiftRpm: 7000,
    baseTone: 95,
    topSpeedKph: 360,
  },
  // Sound-inspired presets: tuning values are simulation settings, not OEM specifications.
  supra: {
    id: "supra",
    name: "Supra-inspired Inline-6 Turbo",
    cylinders: 6,
    gears: 6,
    idleRpm: 800,
    redlineRpm: 7000,
    shiftRpm: 3500,
    baseTone: 52,
    topSpeedKph: 280,
    induction: "turbo",
  },
  skyline: {
    id: "skyline",
    name: "Skyline GT-R-inspired Twin Turbo",
    cylinders: 6,
    gears: 6,
    idleRpm: 900,
    redlineRpm: 8000,
    shiftRpm: 4000,
    baseTone: 55,
    topSpeedKph: 280,
    induction: "turbo",
  },
  golf: {
    id: "golf",
    name: "Golf R-inspired Turbo-4",
    cylinders: 4,
    gears: 7,
    idleRpm: 800,
    redlineRpm: 6500,
    shiftRpm: 3000,
    baseTone: 48,
    topSpeedKph: 250,
    induction: "turbo",
  },
  civic: {
    id: "civic",
    name: "Civic Type R-inspired Turbo-4",
    cylinders: 4,
    gears: 6,
    idleRpm: 850,
    redlineRpm: 7000,
    shiftRpm: 3800,
    baseTone: 54,
    topSpeedKph: 270,
    induction: "turbo",
  },
  v10: {
    id: "v10",
    name: "Lamborghini-inspired V10",
    cylinders: 10,
    gears: 7,
    idleRpm: 950,
    redlineRpm: 8500,
    shiftRpm: 4500,
    baseTone: 70,
    topSpeedKph: 320,
  },
} satisfies Record<string, VehicleProfile>;

export type ProfileId = keyof typeof CAR_PROFILES;
export function isProfileId(value: string): value is ProfileId {
  return Object.hasOwn(CAR_PROFILES, value);
}
